using System.Collections.Generic;
using System.Globalization;

namespace PuzzleGame.Runtime.Services
{
    public static class Localization
    {
        // Stable keys are shared by generated scene labels and live game messages.
        public static readonly Dictionary<string, string[]> Entries = new Dictionary<string, string[]> {
            { "playTab", new[] { "플레이", "Play" } },
            { "helpTab", new[] { "도움말", "Help" } },
            { "manualHint", new[] { "힌트 / H", "Hint / H" } },
            { "quickHelp", new[] { "도움말", "Help" } },
            { "autoHints", new[] { "자동 힌트", "Automatic hints" } },
            { "hintDelay", new[] { "힌트 대기 / {0}초", "Hint delay / {0}s" } },
            { "hintAdvice", new[] { "남은 목표와 특수 캔디 생성을 고려해 추천해요.\nH 키로 언제든 힌트를 요청할 수 있어요.", "Hints favor unfinished goals and special candies.\nPress H whenever you need a hint." } },
            { "animationSpeed", new[] { "연출 속도 / {0}배", "Animation speed / {0}x" } },
            { "controls", new[] { "방향키: 칸 이동 / Enter: 선택 / 교환\n1~4: 아이템 / H: 힌트 / F1: 도움말\nEsc: 선택 취소 / 설정", "Arrows: move cursor / Enter: select / swap\n1-4: items / H: hint / F1: help\nEsc: cancel selection / settings" } },
            { "leaveTitle", new[] { "진행을 그만둘까요?", "Leave this attempt?" } },
            { "leaveBody", new[] { "이번 판의 보드와 남은 이동은 저장되지 않아요.\n이미 사용한 아이템은 돌아오지 않아요.", "This board and remaining moves will not be saved.\nItems already used will not be returned." } },
            { "leaveAction", new[] { "맵으로 이동", "Go to map" } },
            { "restartAction", new[] { "다시 시작", "Restart" } },
            { "restartTitle", new[] { "다시 시작할까요?", "Restart this attempt?" } },
            { "newBest", new[] { "최고 기록 갱신!  이전 {0}점", "New best!  Previous: {0}" } },
            { "resultStats", new[] { "사용 이동 {0}회 / 아이템 {1}개", "Moves used: {0} / Items: {1}" } },
            { "rating", new[] { "별 {0} / 3", "Stars {0} / 3" } },
            { "ratingRules", new[] { "클리어 +1 / 아이템 없이 +1\n기본 이동 {0}회 이상 남기기 +1", "Clear +1 / No items +1\nReserve at least {0} original moves +1" } },
            { "cleanMedal", new[] { "아이템 없이 클리어", "No-item clear" } },
            { "efficientMedal", new[] { "여유 이동 달성", "Moves to spare" } },
            { "medalEarned", new[] { "획득", "Earned" } },
            { "medalOpen", new[] { "도전 중", "To earn" } },
            { "ratingExcluded", new[] { "P 클리어 / 별과 메달은 정상 플레이에서 획득해요", "P clear / Earn stars and medals through normal play" } },
            { "goalDone", new[] { "완료", "Complete" } },
            { "goalShort", new[] { "{0} 부족", "{0} short" } },
            { "rewardPreview", new[] { "첫 클리어 보상", "First-clear reward" } },
            { "rewardClaimed", new[] { "첫 클리어 보상 수령 완료", "First-clear reward claimed" } },
            { "rewardCap", new[] { "보유 한도 99개 / 초과분은 적립되지 않아요", "Stock limit: 99 / Excess is not stored" } },
            { "lockedStage", new[] { "스테이지 {0} 클리어 후 열려요", "Clear stage {0} to unlock" } },
            { "stageLocked", new[] { "잠긴 스테이지", "Locked stage" } },
            { "worldProgress", new[] { "이 월드 {0}/10  /  별 {1}/30", "This world {0}/10  /  Stars {1}/30" } },
            { "campaignStars", new[] { "전체 {0}/50  /  별 {1}/150", "Total {0}/50  /  Stars {1}/150" } },
            { "nextReward", new[] { "다음 4종 보상 / 스테이지 {0}", "Next four-item reward / Stage {0}" } },
            { "allRewards", new[] { "모든 첫 클리어 보상을 받았어요", "All first-clear rewards claimed" } },
            { "unlockedPath", new[] { "새 길이 열렸어요!", "A new path is open!" } },
            { "mapShort", new[] { "맵", "Map" } },
            { "ratingMarks", new[] { "★", "★" } },
            { "items", new[] { "아이템", "Items" } },
            { "itemHammer", new[] { "캔디 망치", "Hammer" } },
            { "itemBomb", new[] { "캔디 폭탄", "Bomb" } },
            { "itemShuffle", new[] { "전체 섞기", "Shuffle" } },
            { "itemExtraMoves", new[] { "이동 +5", "Moves +5" } },
            { "itemHammerHelp", new[] { "선택한 캔디 1개를 깨뜨려요.\n얼음이 있으면 한 겹만 깨고 안의 캔디는 남아요.", "Break one selected candy.\nIf frozen, break one ice layer and keep the candy." } },
            { "itemBombHelp", new[] { "선택한 칸 주변 3x3을 터뜨려요.\n얼음은 한 겹만 깨고, 얼지 않은 특수 캔디는 발동해요.", "Burst a 3x3 area around the selected cell.\nIce absorbs one hit. Unfrozen special candies activate." } },
            { "itemShuffleHelp", new[] { "얼지 않은 캔디만 새롭게 섞어요.\n얼음 속 캔디와 얼음은 제자리에 고정돼요.", "Shuffle only unfrozen candies.\nFrozen candies and their ice stay in place." } },
            { "shuffleUnavailable", new[] { "얼음 속 캔디는 섞을 수 없어요.\n현재 배치에서는 섞을 수 없어 아이템을 쓰지 않았어요.", "Frozen candies cannot shuffle.\nNo playable arrangement was found. Your item was kept." } },
            { "boardBlocked", new[] { "얼음 때문에 더 움직일 수 없어요.\n다시 도전해서 얼음을 먼저 풀어 보세요!", "The ice has left no possible moves.\nTry again and free the frozen candies!" } },
            { "itemExtraMovesHelp", new[] { "이번 스테이지의 남은 이동을 5회 늘려요.\n실패하기 전에 사용하세요.", "Add 5 moves to this attempt.\nUse before the stage ends." } },
            { "itemOwned", new[] { "보유 {0}개 / 최대 99개", "Owned: {0} / 99" } },
            { "itemRules", new[] { "이동 횟수를 소모하지 않아요. 사용하면 1개 차감돼요.\n대상 선택은 Esc / 우클릭 / 취소 버튼으로 취소할 수 있어요.", "Costs 1 item, with no move cost.\nCancel targeting with Esc, right-click or the close button." } },
            { "itemEarn", new[] { "처음에는 각 3개씩 드려요. 스테이지 첫 클리어마다\n망치 > 폭탄 > 섞기 > 이동 순서로 1개를 받아요.\n5번째 스테이지마다 대신 4종을 각 1개씩 받아요.", "Start with 3 of each. First stage clears give 1 item in\nHammer > Bomb > Shuffle > Moves order.\nEvery 5th stage gives 1 of each instead." } },
            { "itemChoose", new[] { "대상 선택", "Choose target" } },
            { "itemUse", new[] { "1개 사용", "Use 1 item" } },
            { "itemEmpty", new[] { "보유 아이템 없음", "No items left" } },
            { "itemTarget", new[] { "{0} / 사용할 캔디를 클릭하세요", "{0} / Click a candy to use" } },
            { "itemSaveFailed", new[] { "아이템을 저장하지 못해 사용하지 않았어요.\n저장 공간을 확인한 뒤 다시 시도해 주세요.", "The item could not be saved, so it was not used.\nCheck storage and try again." } },
            { "itemUnavailable", new[] { "지금은 사용할 수 없어요. 아이템은 차감되지 않았어요.", "Cannot use that item now. No item was spent." } },
            { "itemReward", new[] { "첫 클리어 보상 / {0} +1", "First-clear reward / {0} +1" } },
            { "itemRewardAll", new[] { "첫 클리어 보상 / 아이템 4종 각 +1", "First-clear reward / +1 of every item" } },
            { "settings", new[] { "설정", "Settings" } },
            { "display", new[] { "화면", "Display" } },
            { "resolution", new[] { "해상도", "Resolution" } },
            { "windowed", new[] { "창모드", "Windowed" } },
            { "windowHint", new[] { "체크를 해제하면 전체 화면으로 전환됩니다.", "Uncheck to use full screen." } },
            { "displayHint", new[] { "화면에 맞는 크기를 선택하세요.", "Choose a screen size." } },
            { "displaySaved", new[] { "화면 설정을 적용했어요.", "Display settings applied." } },
            { "saveFailed", new[] { "설정을 저장하지 못했어요. 다시 시도해 주세요.", "Settings could not be saved. Please retry." } },
            { "apply", new[] { "적용", "Apply" } },
            { "resume", new[] { "계속하기", "Resume" } },
            { "quit", new[] { "게임 종료", "Quit" } },
            { "retry", new[] { "다시 하기", "Retry" } },
            { "tryAgain", new[] { "다시 시도", "Try again" } },
            { "next", new[] { "다음 스테이지", "Next stage" } },
            { "back", new[] { "뒤로 가기", "Back" } },
            { "map", new[] { "로드맵", "World map" } },
            { "mapLink", new[] { "맵 보기", "World map" } },
            { "score", new[] { "점수", "Score" } },
            { "currentScore", new[] { "현재 점수", "Score" } },
            { "targetScore", new[] { "목표 점수", "Target" } },
            { "currentPosition", new[] { "현재 위치", "You are here" } },
            { "comboLines", new[] { "줄무늬 조합!", "Striped combo!" } },
            { "comboBomb", new[] { "포장 사탕 조합!", "Wrapped combo!" } },
            { "comboRainbow", new[] { "무지개 조합!", "Rainbow combo!" } },
            { "target", new[] { "목표", "Target" } },
            { "moves", new[] { "남은 이동", "Moves left" } },
            { "music", new[] { "배경음", "Music" } },
            { "effects", new[] { "효과음", "Sound effects" } },
            { "mute", new[] { "음소거", "Mute" } },
            { "language", new[] { "언어", "Language" } },
            { "reduce", new[] { "이펙트 감소", "Reduce effects" } },
            { "preferences", new[] { "소리 / 언어 / 접근성", "Audio, language & accessibility" } },
            { "audioTab", new[] { "소리", "Audio" } },
            { "experienceTab", new[] { "플레이", "Play" } },
            { "otherTab", new[] { "도움말", "Help" } },
            { "on", new[] { "켜짐", "On" } },
            { "off", new[] { "꺼짐", "Off" } },
            { "autoSaved", new[] { "변경한 설정은 자동으로 저장돼요.", "Changes are saved automatically." } },
            { "reduceHint", new[] { "반짝임, 입자, 버튼의 움직임을 줄여요.\n게임 규칙과 점수는 그대로 유지돼요.", "Reduce sparkles, particles and button motion.\nGameplay and scoring stay the same." } },
            { "resetHint", new[] { "진행 초기화는 완료 기록, 최고 점수와 아이템을 초기화해요.\n소리, 언어, 화면 설정은 유지돼요.", "Reset clears stage records and resets item inventory.\nYour audio, language and display settings are kept." } },
            { "stageTitle", new[] { "스테이지 {0}", "Stage {0}" } },
            { "moveLimit", new[] { "이동 횟수", "Move limit" } },
            { "bestScore", new[] { "최고 기록", "Best score" } },
            { "noRecord", new[] { "첫 도전", "First try" } },
            { "allGoals", new[] { "아래 목표를 모두 달성하세요", "Complete every goal below" } },
            { "scoreAmount", new[] { "{0:N0}점", "{0:N0} pts" } },
            { "candyName", new[] { "{0} 사탕", "{0} candies" } },
            { "candyAmount", new[] { "{0}개", "{0}" } },
            { "clearFrost", new[] { "얼음 제거", "Clear Frost" } },
            { "tileAmount", new[] { "{0}칸", "{0} tiles" } },
            { "credits", new[] { "크레딧", "Credits" } },
            { "reset", new[] { "진행 초기화", "Reset progress" } },
            { "resetConfirm", new[] { "완료 기록과 최고 점수를 지우고 아이템을 초기화할까요?\n이 작업은 되돌릴 수 없습니다.", "Erase stage records and reset item inventory?\nThis cannot be undone." } },
            { "resetDone", new[] { "진행 기록을 초기화했어요.", "Progress has been reset." } },
            { "resetFailed", new[] { "초기화하지 못했어요. 저장 위치를 확인한 뒤 다시 시도해 주세요.", "Progress could not be reset. Check the save location and retry." } },
            { "cancel", new[] { "취소", "Cancel" } },
            { "close", new[] { "닫기", "Close" } },
            { "start", new[] { "시작", "Play" } },
            { "ok", new[] { "확인", "OK" } },
            { "recovered", new[] { "저장 파일에 문제가 있어 이전 백업에서 진행 기록을 복구했어요.", "Progress was recovered from the previous backup." } },
            { "damaged", new[] { "저장 파일과 백업을 읽지 못해 새 진행으로 시작했어요.", "Neither save nor backup could be read. Starting a new campaign." } },
            { "mapSummary", new[] { "이 월드 {0} / 10    전체 {1} / 50", "World {0} / 10    Total {1} / 50" } },
            { "challenge", new[] { "{0} 도전하기", "Play {0}" } },
            { "replayFinal", new[] { "5-10 다시 하기", "Replay 5-10" } },
            { "preview", new[] { "스테이지 {0}\n이동 {1}회 / 목표 {2:N0}점\n최고 기록 {3:N0}점", "Stage {0}\n{1} moves / Target {2:N0}\nBest score {3:N0}" } },
            { "collect", new[] { "{0} 사탕 {1}개", "{0} candies: {1}" } },
            { "red", new[] { "빨강", "Red" } }, { "orange", new[] { "주황", "Orange" } },
            { "yellow", new[] { "노랑", "Yellow" } }, { "green", new[] { "초록", "Green" } },
            { "blue", new[] { "파랑", "Blue" } }, { "purple", new[] { "보라", "Purple" } },
            { "frost", new[] { "얼음 {0} / {1}", "Frost {0} / {1}" } },
            { "frostTarget", new[] { "얼음 바닥 {0}칸 제거", "Clear {0} Frost tiles" } },
            { "won", new[] { "스테이지 성공!", "Stage clear!" } },
            { "lost", new[] { "스테이지 실패", "Try again!" } },
            { "resultScore", new[] { "획득 {0:N0}점  /  목표 {1:N0}점", "Score {0:N0}  /  Target {1:N0}" } },
            { "wonMessage", new[] { "모든 목표를 달성했어요!\n남은 이동 {0}회", "All goals complete!\n{0} moves remaining" } },
            { "lostMessage", new[] { "이동 횟수를 모두 사용했어요.\n다시 도전해 보세요!", "No moves left.\nGive it another try!" } },
            { "progressFailed", new[] { "진행 기록을 저장하지 못했어요.", "Progress could not be saved." } },
            { "complete", new[] { "사탕 왕국 완주!", "Candy kingdom complete!" } },
            { "completeMessage", new[] { "5개 월드, 50개 스테이지를 모두 클리어했어요!\n왕국의 모든 사탕이 빛나요. 고마워요!", "All 5 worlds and 50 stages cleared!\nThe whole kingdom sparkles. Thank you for playing!" } },
            { "resolving", new[] { "블록을 정리하는 중...", "Clearing candies..." } },
            { "resultHint", new[] { "아래 결과를 확인하세요", "See your result below" } },
            { "dragHint", new[] { "블록을 누른 채 옆으로 끌어 놓으세요", "Drag a candy to an adjacent tile" } },
            { "loading", new[] { "불러오는 중", "Loading" } },
            { "loadFailed", new[] { "불러오지 못했어요. 다시 시도해 주세요.", "Could not load. Please try again." } },
            { "tutorial1", new[] { "사탕을 옆 칸으로 끌어 같은 색 3개를 맞춰 보세요.\n빛나는 두 칸이 교환할 수 있는 예시예요.", "Drag a candy one tile to match 3 of the same color.\nThe highlighted pair shows a possible move." } },
            { "tutorial2", new[] { "정해진 이동 안에 점수와 사탕 수집 목표를 모두 채워요.\n매치가 없는 교환은 이동을 사용하지 않아요.", "Reach the score and collection goals within the move limit.\nSwaps without a match do not cost a move." } },
            { "tutorial3", new[] { "4개를 일렬로 맞추면 줄무늬 사탕이 생겨요.\n줄무늬 사탕을 매치하면 한 줄을 지워요.", "Match 4 in a line to create a striped candy.\nMatch it again to clear an entire row or column." } },
            { "tutorial4", new[] { "T/L 모양은 포장 사탕, 5개 직선은 무지개 사탕!\n특수 사탕끼리 교환하면 더 큰 효과가 나요.", "T and L matches make wrapped candies; a line of 5 makes a rainbow.\nSwap special candies together for bigger effects!" } },
            { "tutorial5", new[] { "얼음 속 캔디는 움직일 수 없어요. 같은 색과 매치하거나\n특수 효과 / 아이템으로 얼음을 모두 깨면 풀려나요!", "Frozen candies cannot move. Match their color or hit them\nwith a special or item to break the ice and free them!" } },
            { "tutorialTitle", new[] { "플레이 안내 {0} / 5", "How to play {0} / 5" } },
            { "help", new[] { "그림으로 보는 도움말", "Illustrated guide" } },
            { "guideBasic", new[] { "기본", "Basics" } },
            { "guideSpecial", new[] { "특수 캔디", "Specials" } },
            { "guideFrost", new[] { "얼음", "Ice" } },
            { "guideItems", new[] { "아이템", "Items" } },
            { "guideSwap", new[] { "옆 칸으로 끌어 같은 색 3개 이상을 맞춰요. 매치가 없는 교환은 되돌아오며 이동을 쓰지 않아요.", "Drag to an adjacent tile to match 3 or more of one color. A swap without a match returns for free." } },
            { "guideGoals", new[] { "이동이 끝나기 전에 점수, 사탕 수집, 얼음 목표를 모두 채워요. 완료한 목표에는 체크가 생겨요.", "Complete ALL score, candy and ice goals before moves run out. A check marks each completed goal." } },
            { "guideStriped", new[] { "4개 직선 매치: 줄무늬 캔디! 다시 매치하면 줄무늬 방향의 가로 또는 세로 한 줄을 지워요.", "Match 4 in a line to make a striped candy. Match it to clear the row or column shown by its stripes." } },
            { "guideWrapped", new[] { "T / L 모양 매치: 포장 캔디! 다시 매치하면 주변 3x3 영역을 터뜨려요.", "Match a T or L to make a wrapped candy. Match it to burst the surrounding 3x3 area." } },
            { "guideRainbow", new[] { "5개 직선 매치: 무지개 캔디! 옆 캔디와 교환하면 그 색을 모두 지워요. 특수 캔디끼리 교환하면 효과가 커져요.", "Match 5 in a line to make a rainbow. Swap it with a neighbor to clear that color. Swap two special candies for a combined effect." } },
            { "guideIceHit", new[] { "얼음 속 캔디는 교환 / 낙하 / 섞기로 움직이지 않아요. 같은 색과 매치하거나 특수 효과 / 아이템으로 맞히면 얼음 한 겹이 깨져요.", "Frozen candies cannot swap, fall or shuffle. Match their color or hit them with a special or item to break one ice layer." } },
            { "guideIceGoal", new[] { "얼음이 맞는 동안 안의 캔디는 남아요. 마지막 겹까지 깨야 움직이고, 완전히 깬 얼음만 목표에 더해져요.", "Ice absorbs the hit and keeps its candy. Break the last layer to free it. Only fully broken ice counts toward the goal." } },
            { "guideIceShuffle", new[] { "얼어 있는 특수 캔디도 해동 전에는 발동하지 않아요. 얼음에 막힌 빈칸에는 새 캔디가 그 자리에서 나타나요.", "Frozen specials stay dormant until freed. New candies appear in pockets below ice without falling through it." } },
            { "colorLabels", new[] { "캔디 숫자 표시", "Candy numbers" } },
            { "colorLabelsHint", new[] { "색 구분이 어려우면 설정 > 언어 / 효과에서 켜세요. 같은 캔디와 수집 목표에 같은 숫자를 표시해요.", "Enable in Language / effects to identify colors by number. Matching candies and collection goals share a number." } },
            { "testSound", new[] { "효과음 들어보기", "Preview sound" } },
            { "itemHammerShort", new[] { "망치", "Hammer" } },
            { "itemBombShort", new[] { "폭탄", "Bomb" } },
            { "itemShuffleShort", new[] { "섞기", "Shuffle" } },
            { "itemExtraMovesShort", new[] { "+5", "+5" } },
            { "feedback", new[] { "어려웠던 점 남기기", "What made this difficult?" } },
            { "luck", new[] { "필요한 사탕이 안 나옴", "Needed candies did not appear" } },
            { "fewMoves", new[] { "이동 횟수 부족", "Not enough moves" } },
            { "unclear", new[] { "목표/규칙이 어려움", "Goals or rules were unclear" } },
            { "feedbackSaved", new[] { "의견을 기기에 기록했어요. 고마워요!", "Feedback saved on this device. Thank you!" } },
            { "creditsBody", new[] { "기획 / 개발: minseok5408\n사탕 / 배경: 프로젝트 자체 제작 AI 이미지\n음악 / 효과음: 프로젝트 자체 합성 음원\n글꼴: Jua, Bagel Fat One, Nanum Gothic (SIL OFL)\nUnity / TextMesh Pro / Liberation Sans (SIL OFL)\nEmojiOne (CC BY 4.0)\n자세한 라이선스는 빌드의 ThirdPartyNotices 폴더를 확인하세요.", "Design & development: minseok5408\nCandy & backgrounds: project AI-generated artwork\nMusic & sounds: original synthesized audio\nFonts: Jua, Bagel Fat One, Nanum Gothic (SIL OFL)\nUnity, TextMesh Pro, Liberation Sans (SIL OFL)\nEmojiOne (CC BY 4.0)\nSee ThirdPartyNotices in the game folder for licenses." } }
        };
        public static string Get(string key, params object[] args)
        {
            if (!Entries.TryGetValue(key, out var values)) return key;
            string text = values[GamePreferences.Current.language == "en" ? 1 : 0];
            return args.Length == 0 ? text : string.Format(CultureInfo.InvariantCulture, text, args);
        }
        public static string World(int world) => GamePreferences.Current.language == "en"
            ? new[] { "SUGAR GARDEN", "ORANGE ORCHARD", "ICE SODA", "GRAPE NIGHT GARDEN", "RAINBOW PALACE" }[world-1]
            : new[] { "사탕 정원", "오렌지 과수원", "얼음 소다", "포도 밤정원", "무지개 궁전" }[world-1];
    }
}
